# Generated by Django 5.0.1 on 2024-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
