# Generated by Django 5.0.1 on 2024-02-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_product_stock_variant_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='stock',
            new_name='stock_level',
        ),
    ]
