# Generated by Django 4.2.9 on 2024-03-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='Product',
            new_name='product',
        ),
    ]
