# Generated by Django 4.2.9 on 2024-03-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, help_text='A brief description of image', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
